# Generated by Django 3.2.4 on 2021-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('Nocategory', 'Nocategory'), ('Kazkah', 'Kazakh'), ('Russian pop', 'Russian_pop'), ('Kpop', 'Kpop')], default='Nocategory', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-hop', 'Hip-hop'), ('Classic', 'Classic'), ('Jazz', 'Jazz'), ('Rap', 'Rap')], default='Pop', max_length=20),
        ),
    ]
