# Generated by Django 3.2.4 on 2021-06-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0009_auto_20210616_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock')], default='Pop', max_length=20),
        ),
    ]
